{
 "title": "Gin Metrics",
 "tags": [
  "go",
  "gin"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Project", "query": { "query": "label_values(job)" } },
   {
    "name": "Instance",
    "query": {
     "query": "label_values({job=\"$Project\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "PV Rate(5M)",
   "type": "gauge",
   "description": "Application request rate every 5 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(im_request_total{job=\"$Project\",instance=\"$Instance\"}[5m])"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(im_request_total{job=\"$Project\",instance=\"$Instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "UV",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(im_request_uv_total{job=\"$Project\",instance=\"$Instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Traffic In-Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(im_request_body_total{job=\"$Project\",instance=\"$Instance\"}[5m])",
     "legendFormat": "{{instance}}-in"
    },
    {
     "expr": "rate(im_response_body_total{job=\"$Project\",instance=\"$Instance\"}[5m])",
     "legendFormat": "{{instance}}-out"
    }
   ]
  },
  {
   "title": "URI Request",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by(uri, instance) (im_request_uri_total{job=\"$Project\", instance=\"$Instance\"}))",
     "legendFormat": "{{instance}} {{uri}}"
    }
   ]
  },
  {
   "title": "HTTP Method",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method, instance) (im_request_uri_total{job=\"$Project\",instance=\"$Instance\"})",
     "legendFormat": "{{instance}}-{{method}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum (rate(im_request_duration_bucket{job=\"$Project\",instance=\"$Instance\"}[5m])) by (le, instance))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum (rate(im_request_duration_bucket{job=\"$Project\",instance=\"$Instance\"}[5m])) by (le, instance))",
     "legendFormat": "P99"
    },
    {
     "expr": "sum (im_request_duration_sum{job=\"$Project\",instance=\"$Instance\"}) / sum(im_request_duration_count{job=\"$Project\",instance=\"$Instance\"})",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "Status Code",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(code, instance) (im_request_uri_total{job=\"$Project\",instance=\"$Instance\"})",
     "legendFormat": "{{instance}}-{{code}}"
    }
   ]
  },
  {
   "title": "Slow Request(default 2s)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(uri, instance) (im_request_slows_total{job=\"$Project\",instance=\"$Instance\"})",
     "legendFormat": "{{instance}}-{{uri}}"
    }
   ]
  }
 ]
}